# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JSON-Streaming-Reader
version:      0.04
version_from: lib/JSON/Streaming/Reader.pm
installdirs:  site
requires:
    B:                             0
    Carp:                          0
    IO::File:                      0
    IO::Scalar:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
